// <auto-generated />
using System;
using Data_Base.App_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Base.Migrations
{
    [DbContext(typeof(Db_Context))]
    partial class Db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data_Base.Models.A.Answers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answers_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Points_Earned")
                        .HasColumnType("float");

                    b.Property<int>("Question_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Right_Answer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Question_Id");

                    b.ToTable("Answerses");
                });

            modelBuilder.Entity("Data_Base.Models.C.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Class_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Grade_Id")
                        .HasColumnType("int");

                    b.Property<int>("Max_Student")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Grade_Id");

                    b.HasIndex("Teacher_Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Exam_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_HisTory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Actual_Execution_Time")
                        .HasColumnType("bigint");

                    b.Property<long>("Create_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Exam_Room_Student_Id")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Room_Student_Id");

                    b.ToTable("Exam_HisTories");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("End_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Exam_Id")
                        .HasColumnType("int");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<long>("Start_Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Id");

                    b.HasIndex("Room_Id");

                    b.ToTable("Exam_Rooms");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Exam_Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Package_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Room_Id");

                    b.HasIndex("Package_Id");

                    b.ToTable("Exam_Room_Packages");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Check_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Exam_Room_Package_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Test_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Room_Package_Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Test_Id");

                    b.ToTable("Exam_Room_Students");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Student_Answer_HisTory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Answer_Id")
                        .HasColumnType("int");

                    b.Property<int>("Exam_Room_Student_Id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Answer_Id");

                    b.HasIndex("Exam_Room_Student_Id");

                    b.ToTable("Exam_Room_Student_Answer_HisTories");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Exam_Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Room_Id");

                    b.HasIndex("Teacher_Id");

                    b.ToTable("Exam_Room_Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.G.Grade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Grade_Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Data_Base.Models.L.Learning_Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Attendance")
                        .HasColumnType("float");

                    b.Property<double>("Point_15")
                        .HasColumnType("float");

                    b.Property<double>("Point_45")
                        .HasColumnType("float");

                    b.Property<double>("Point_Final")
                        .HasColumnType("float");

                    b.Property<double>("Point_Midterm")
                        .HasColumnType("float");

                    b.Property<double>("Point_Summary")
                        .HasColumnType("float");

                    b.Property<int?>("Point_TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.Property<int>("Summary_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Point_TypeId");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Summary_ID");

                    b.ToTable("Learning_Summaries");
                });

            modelBuilder.Entity("Data_Base.Models.P.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Class_Id")
                        .HasColumnType("int");

                    b.Property<long>("Create_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_Questions")
                        .HasColumnType("int");

                    b.Property<int>("Package_Code")
                        .HasColumnType("int");

                    b.Property<string>("Package_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Package_Type_Id")
                        .HasColumnType("int");

                    b.Property<int>("Point_Type_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Package_Type_Id");

                    b.HasIndex("Point_Type_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Data_Base.Models.P.Package_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Package_Type_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Package_Types");
                });

            modelBuilder.Entity("Data_Base.Models.P.Point_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Point_Type_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Point_Types");
                });

            modelBuilder.Entity("Data_Base.Models.P.Point_Type_Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Point_Type_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Point_Type_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Point_Type_Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long?>("Maximum_Score")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Package_Id")
                        .HasColumnType("int");

                    b.Property<int>("Question_Level_Id")
                        .HasColumnType("int");

                    b.Property<string>("Question_Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Question_Type_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Package_Id");

                    b.HasIndex("Question_Level_Id");

                    b.HasIndex("Question_Type_Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question_Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Question_Level_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question_Levels");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Package_Type_Id")
                        .HasColumnType("int");

                    b.Property<string>("Question_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Package_Type_Id");

                    b.ToTable("Question_Types");
                });

            modelBuilder.Entity("Data_Base.Models.R.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Data_Base.Models.R.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Room_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Data_Base.Models.S.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Point")
                        .HasColumnType("float");

                    b.Property<int>("Point_Type_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.Property<int>("Summary_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Point_Type_Id");

                    b.HasIndex("Student_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Summary_Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Data_Base.Models.S.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Student_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Data_Base.Models.S.Student_Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Class_Id")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Student_Classes");
                });

            modelBuilder.Entity("Data_Base.Models.S.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Subject_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.S.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("End_Time")
                        .HasColumnType("bigint");

                    b.Property<long>("Start_Time")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("Data_Base.Models.T.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Teacher_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.T.Teacher_Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.Property<int>("Teacher_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Teacher_id");

                    b.ToTable("Teacher_Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.T.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Package_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<string>("Test_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Package_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Data_Base.Models.T.Test_Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Question_Id")
                        .HasColumnType("int");

                    b.Property<int>("Test_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Question_Id");

                    b.HasIndex("Test_Id");

                    b.ToTable("Test_Questions");
                });

            modelBuilder.Entity("Data_Base.Models.U.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Create_Time")
                        .HasColumnType("bigint");

                    b.Property<long>("Data_Of_Birth")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Last_Mordification_Time")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("User_Pass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data_Base.V_Model.V_Package", b =>
                {
                    b.Property<string>("Class_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Create_Time")
                        .HasColumnType("bigint");

                    b.Property<long>("End_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Exam_Id")
                        .HasColumnType("int");

                    b.Property<string>("Exam_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Exam_Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Number_Of_Questions")
                        .HasColumnType("int");

                    b.Property<int>("Package_Code")
                        .HasColumnType("int");

                    b.Property<string>("Package_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Package_Type_Id")
                        .HasColumnType("int");

                    b.Property<string>("Package_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point_Type_Id")
                        .HasColumnType("int");

                    b.Property<string>("Point_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<string>("Room_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Start_Time")
                        .HasColumnType("bigint");

                    b.Property<int>("Subject_Id")
                        .HasColumnType("int");

                    b.Property<string>("Subject_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teaacher_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher_Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Teacher_Data_Of_Birth")
                        .HasColumnType("bigint");

                    b.Property<string>("Teacher_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher_Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher_Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToView("V_Package");
                });

            modelBuilder.Entity("Data_Base.V_Model.V_Student", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Create_Time")
                        .HasColumnType("bigint");

                    b.Property<long>("Data_Of_Birth")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.ToView("V_Student");
                });

            modelBuilder.Entity("Data_Base.Models.A.Answers", b =>
                {
                    b.HasOne("Data_Base.Models.Q.Question", "Questions")
                        .WithMany("Answerses")
                        .HasForeignKey("Question_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Data_Base.Models.C.Class", b =>
                {
                    b.HasOne("Data_Base.Models.G.Grade", "Grades")
                        .WithMany("Classes")
                        .HasForeignKey("Grade_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.T.Teacher", "Teachers")
                        .WithMany()
                        .HasForeignKey("Teacher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grades");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam", b =>
                {
                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("Exams")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_HisTory", b =>
                {
                    b.HasOne("Data_Base.Models.E.Exam_Room_Student", "Exam_Room_Students")
                        .WithMany("Exam_HisTories")
                        .HasForeignKey("Exam_Room_Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam_Room_Students");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room", b =>
                {
                    b.HasOne("Data_Base.Models.E.Exam", "Exams")
                        .WithMany("Exam_Rooms")
                        .HasForeignKey("Exam_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.R.Room", "Rooms")
                        .WithMany("Exam_Room")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Package", b =>
                {
                    b.HasOne("Data_Base.Models.E.Exam_Room", "Exam_Rooms")
                        .WithMany("Exam_Room_Packages")
                        .HasForeignKey("Exam_Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.P.Package", "Packages")
                        .WithMany("Exam_Room_Packages")
                        .HasForeignKey("Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam_Rooms");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Student", b =>
                {
                    b.HasOne("Data_Base.Models.E.Exam_Room_Package", "Exam_Room_Packages")
                        .WithMany()
                        .HasForeignKey("Exam_Room_Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Student", "Students")
                        .WithMany("Exam_Room_Students")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.T.Test", "Tests")
                        .WithMany("Exam_Room_Students")
                        .HasForeignKey("Test_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam_Room_Packages");

                    b.Navigation("Students");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Student_Answer_HisTory", b =>
                {
                    b.HasOne("Data_Base.Models.A.Answers", "Answers")
                        .WithMany("Exam_Room_Student_Answer_HisTories")
                        .HasForeignKey("Answer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.E.Exam_Room_Student", "Exam_Room_Students")
                        .WithMany("Exam_Room_Student_Answer_HisTories")
                        .HasForeignKey("Exam_Room_Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answers");

                    b.Navigation("Exam_Room_Students");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Teacher", b =>
                {
                    b.HasOne("Data_Base.Models.E.Exam_Room", "Exam_Rooms")
                        .WithMany("Exam_Room_Teachers")
                        .HasForeignKey("Exam_Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.T.Teacher", "Teachers")
                        .WithMany("Exam_Room_Teachers")
                        .HasForeignKey("Teacher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam_Rooms");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.L.Learning_Summary", b =>
                {
                    b.HasOne("Data_Base.Models.P.Point_Type", null)
                        .WithMany("Learning_Summaries")
                        .HasForeignKey("Point_TypeId");

                    b.HasOne("Data_Base.Models.S.Student", "Students")
                        .WithMany("Learning_Summaries")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("Learning_Summaries")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Summary", "Summaries")
                        .WithMany("Learning_Summaries")
                        .HasForeignKey("Summary_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("Data_Base.Models.P.Package", b =>
                {
                    b.HasOne("Data_Base.Models.C.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.P.Package_Type", "Package_Types")
                        .WithMany("Packages")
                        .HasForeignKey("Package_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.P.Point_Type", "Point_Types")
                        .WithMany("Packages")
                        .HasForeignKey("Point_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("Packages")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Package_Types");

                    b.Navigation("Point_Types");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.P.Point_Type_Subject", b =>
                {
                    b.HasOne("Data_Base.Models.P.Point_Type", "Point_Types")
                        .WithMany("Point_Type_Subjects")
                        .HasForeignKey("Point_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("PointType_Subjects")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point_Types");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question", b =>
                {
                    b.HasOne("Data_Base.Models.P.Package", "Packages")
                        .WithMany("Questions")
                        .HasForeignKey("Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.Q.Question_Level", "Question_Levels")
                        .WithMany("Questions")
                        .HasForeignKey("Question_Level_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.Q.Question_Type", "Question_Types")
                        .WithMany("Questions")
                        .HasForeignKey("Question_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packages");

                    b.Navigation("Question_Levels");

                    b.Navigation("Question_Types");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question_Type", b =>
                {
                    b.HasOne("Data_Base.Models.P.Package_Type", "Package_Types")
                        .WithMany()
                        .HasForeignKey("Package_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package_Types");
                });

            modelBuilder.Entity("Data_Base.Models.S.Score", b =>
                {
                    b.HasOne("Data_Base.Models.P.Point_Type", "Point_Types")
                        .WithMany("Scores")
                        .HasForeignKey("Point_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Student", "Students")
                        .WithMany("Scores")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("Scores")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Summary", "Summaries")
                        .WithMany("Scores")
                        .HasForeignKey("Summary_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point_Types");

                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("Data_Base.Models.S.Student", b =>
                {
                    b.HasOne("Data_Base.Models.U.User", "Users")
                        .WithMany("Students")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data_Base.Models.S.Student_Class", b =>
                {
                    b.HasOne("Data_Base.Models.C.Class", "Classes")
                        .WithMany("Student_Classes")
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Student", "Students")
                        .WithMany("Student_Classes")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Data_Base.Models.T.Teacher", b =>
                {
                    b.HasOne("Data_Base.Models.U.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data_Base.Models.T.Teacher_Subject", b =>
                {
                    b.HasOne("Data_Base.Models.S.Subject", "Subjects")
                        .WithMany("Teacher_Subject")
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.T.Teacher", "Teachers")
                        .WithMany("Teacher_Subject")
                        .HasForeignKey("Teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.T.Test", b =>
                {
                    b.HasOne("Data_Base.Models.P.Package", "Packages")
                        .WithMany()
                        .HasForeignKey("Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.S.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packages");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Data_Base.Models.T.Test_Question", b =>
                {
                    b.HasOne("Data_Base.Models.Q.Question", "Questions")
                        .WithMany("Test_Questions")
                        .HasForeignKey("Question_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Base.Models.T.Test", "Tests")
                        .WithMany("Test_Questions")
                        .HasForeignKey("Test_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Data_Base.Models.U.User", b =>
                {
                    b.HasOne("Data_Base.Models.R.Role", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Data_Base.Models.A.Answers", b =>
                {
                    b.Navigation("Exam_Room_Student_Answer_HisTories");
                });

            modelBuilder.Entity("Data_Base.Models.C.Class", b =>
                {
                    b.Navigation("Student_Classes");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam", b =>
                {
                    b.Navigation("Exam_Rooms");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room", b =>
                {
                    b.Navigation("Exam_Room_Packages");

                    b.Navigation("Exam_Room_Teachers");
                });

            modelBuilder.Entity("Data_Base.Models.E.Exam_Room_Student", b =>
                {
                    b.Navigation("Exam_HisTories");

                    b.Navigation("Exam_Room_Student_Answer_HisTories");
                });

            modelBuilder.Entity("Data_Base.Models.G.Grade", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Data_Base.Models.P.Package", b =>
                {
                    b.Navigation("Exam_Room_Packages");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Data_Base.Models.P.Package_Type", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Data_Base.Models.P.Point_Type", b =>
                {
                    b.Navigation("Learning_Summaries");

                    b.Navigation("Packages");

                    b.Navigation("Point_Type_Subjects");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question", b =>
                {
                    b.Navigation("Answerses");

                    b.Navigation("Test_Questions");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question_Level", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Data_Base.Models.Q.Question_Type", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Data_Base.Models.R.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Data_Base.Models.R.Room", b =>
                {
                    b.Navigation("Exam_Room");
                });

            modelBuilder.Entity("Data_Base.Models.S.Student", b =>
                {
                    b.Navigation("Exam_Room_Students");

                    b.Navigation("Learning_Summaries");

                    b.Navigation("Scores");

                    b.Navigation("Student_Classes");
                });

            modelBuilder.Entity("Data_Base.Models.S.Subject", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Learning_Summaries");

                    b.Navigation("Packages");

                    b.Navigation("PointType_Subjects");

                    b.Navigation("Scores");

                    b.Navigation("Teacher_Subject");
                });

            modelBuilder.Entity("Data_Base.Models.S.Summary", b =>
                {
                    b.Navigation("Learning_Summaries");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Data_Base.Models.T.Teacher", b =>
                {
                    b.Navigation("Exam_Room_Teachers");

                    b.Navigation("Teacher_Subject");
                });

            modelBuilder.Entity("Data_Base.Models.T.Test", b =>
                {
                    b.Navigation("Exam_Room_Students");

                    b.Navigation("Test_Questions");
                });

            modelBuilder.Entity("Data_Base.Models.U.User", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
